server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html
#    operations-sorter: method

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    statusPageUrlPath: ${server.servletPath}/info
#    healthCheckUrlPath: ${server.servletPath}/health