server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html
#    operations-sorter: method